from pickle import TRUE


WAVEFORM_FILE_PATH = "Waveforms/triangle.csv"
FREQUENCY = 60
VOLTAGE = 5

ADC_AVERAGE_VOLTAGE = 1.65/2

BUFFER_SIZE = 8000

SAMPLE_RATE = (BUFFER_SIZE/4) * FREQUENCY
DUAL_POLARITY = True
